### ISSUE TITLE
Unsupported state or unable to authenticate data

### ISSUE THREAD

**Issue by rafche** [schopenhauer/sage#10]
When i try to gather data, i'm getting this authenticate data Error. I checked my decryption keys twice and also tried to switch positions.

20:12:23.414Z ERROR app: Unsupported state or unable to authenticate data
  Error: Unsupported state or unable to authenticate data
      at Decipheriv.final (internal/crypto/cipher.js:164:28)
      at DecryptDatagram (/home/pi/sage/app.js:71:69)
      at SerialPort.port.on (/home/pi/sage/app.js:134:23)
      at SerialPort.emit (events.js:198:13)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at SerialPort.Readable.push (_stream_readable.js:224:10)
      at binding.read.then (/home/pi/sage/node_modules/@serialport/stream/lib/index.js:385:12)

not sure if the Decryption process fails, or else.

many thanks, cheers Philipp

**Comment by quam426** [comment]
Hello,

I assume you've put in the GAC and GUEK keys as you got it from the network provider's website. For the 'additional_auth_data' I had to add '30' at the beginning of the key - then it worked for me.

cheers,
markus

**Comment by rafche** [comment]
Hi,
many thanks solved my Issue.

cheers
Philipp
